# Generated by Django 3.1.2 on 2020-10-31 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201024_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('referido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='created',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='update_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_ida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_regreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='HotelTipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('capacidad', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotel')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='HotelServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotel')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DestinoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='DestinoHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.destinoturistico')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotel')),
                ('hotel_tipo_habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.hoteltipohabitacion')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.pais')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementoDestino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.complemento')),
                ('destino_turistico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.destinoturistico')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('complementos', models.ManyToManyField(to='app.ComplementoDestino')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.departamento'),
        ),
    ]
