# Generated by Django 3.1.2 on 2020-10-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201031_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.ciudad'),
            preserve_default=False,
        ),
    ]
