# Generated by Django 3.1.2 on 2020-10-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201031_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.CharField(max_length=455),
        ),
        migrations.AlterField(
            model_name='plan',
            name='imagen',
            field=models.CharField(max_length=455),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.CharField(max_length=455),
        ),
    ]
