# Generated by Django 3.1.2 on 2020-10-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201031_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.categoria'),
        ),
    ]
