# Generated by Django 3.1.2 on 2020-11-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201031_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
