# Generated by Django 3.1.2 on 2020-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
