# Generated by Django 3.1.2 on 2020-11-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cliente_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created',
        ),
        migrations.AddField(
            model_name='compras',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClientePlan',
        ),
    ]
