# Generated by Django 3.1.2 on 2020-11-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201116_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='precio',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
