# Generated by Django 3.1.2 on 2020-11-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201116_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
