# Generated by Django 3.1.2 on 2020-11-16 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201116_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='fecha_ida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='fecha_regreso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='servicios',
            field=models.ManyToManyField(to='app.Servicio'),
        ),
        migrations.AddField(
            model_name='compras',
            name='tipo_habitacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.tipohabitacion'),
            preserve_default=False,
        ),
    ]
