# Generated by Django 3.1.2 on 2020-12-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201116_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotel'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='servicios',
            field=models.ManyToManyField(null=True, to='app.Servicio'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='tipo_habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.tipohabitacion'),
        ),
    ]
