# Generated by Django 3.1.2 on 2021-03-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201205_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagar', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FechaPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ida', models.DateTimeField(null=True)),
                ('fecha_regreso', models.DateTimeField(null=True)),
                ('precio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HotelHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('capacidad', models.IntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.habitacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='complementodestino',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='complementodestino',
            name='destino_turistico',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='tipo_habitacion',
        ),
        migrations.RemoveField(
            model_name='destinohotel',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='destinohotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='destinohotel',
            name='hotel_tipo_habitacion',
        ),
        migrations.RemoveField(
            model_name='destinohotel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='hotelservicio',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelservicio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='hoteltipohabitacion',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hoteltipohabitacion',
            name='tipo_habitacion',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tipo_habitaciones',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='destinos',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='fecha_ida',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='fecha_regreso',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='precio',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Complemento',
        ),
        migrations.DeleteModel(
            name='ComplementoDestino',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='DestinoHotel',
        ),
        migrations.DeleteModel(
            name='DestinoTuristico',
        ),
        migrations.DeleteModel(
            name='HotelServicio',
        ),
        migrations.DeleteModel(
            name='HotelTipoHabitacion',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='TipoHabitacion',
        ),
        migrations.AddField(
            model_name='hotelhabitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotel'),
        ),
        migrations.AddField(
            model_name='fechaplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fechas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.fechaplan'),
        ),
        migrations.AddField(
            model_name='factura',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotel'),
        ),
        migrations.AddField(
            model_name='factura',
            name='hotel_habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.hotelhabitacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan'),
        ),
    ]
