# Generated by Django 3.1.2 on 2021-03-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210327_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('comentario', models.CharField(max_length=455)),
                ('calificaion', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='rating',
        ),
        migrations.AlterField(
            model_name='fechaplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fechas', to='app.plan'),
        ),
    ]
