# Generated by Django 3.1.2 on 2021-03-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210328_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan'),
            preserve_default=False,
        ),
    ]
